// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SearchDashboard.Controller.Persistence;

namespace SearchDashboard.Controller.Migrations
{
    [DbContext(typeof(DashboardDbContext))]
    partial class DashboardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SearchDashboard.Controller.Model.SearchToken", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("SearchUrlId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("SearchUrlId");

                    b.ToTable("SearchTokens");
                });

            modelBuilder.Entity("SearchDashboard.Controller.Model.SearchUrl", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("id");

                    b.ToTable("SearchUrls");
                });

            modelBuilder.Entity("SearchDashboard.Controller.Model.SearchToken", b =>
                {
                    b.HasOne("SearchDashboard.Controller.Model.SearchUrl", "SearchUrl")
                        .WithMany("SearchTokens")
                        .HasForeignKey("SearchUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchUrl");
                });

            modelBuilder.Entity("SearchDashboard.Controller.Model.SearchUrl", b =>
                {
                    b.Navigation("SearchTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
